/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package citbyui.cit260.sarahjanis.memory.frames;

import citbyui.cit260.sarahjanis.memory.models.Player;

/**
 *
 * @author Janis
 */
public class BoardMediumFrame extends javax.swing.JFrame {

    /**
     * Creates new form BoardMediumFrame
     */
    public BoardMediumFrame(Player player1, Player player2) {
        initComponents();
        setLocationRelativeTo(null);
        jlP1Name.setText(player1.getName());
        jlP2Name.setText(player2.getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpMTitle = new javax.swing.JPanel();
        jlMTitle = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jlP1Name = new javax.swing.JLabel();
        jlP2Name = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jlP1Matches = new javax.swing.JLabel();
        jlP2Matches = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jlP1Wins = new javax.swing.JLabel();
        jlP2Wins = new javax.swing.JLabel();
        jpMGameArea = new javax.swing.JPanel();
        jbMButton1 = new javax.swing.JButton();
        jbMButton2 = new javax.swing.JButton();
        jbMButton3 = new javax.swing.JButton();
        jbMButton4 = new javax.swing.JButton();
        jbMButton5 = new javax.swing.JButton();
        jbMButton6 = new javax.swing.JButton();
        jbMButton7 = new javax.swing.JButton();
        jbMButton8 = new javax.swing.JButton();
        jbMButton9 = new javax.swing.JButton();
        jbMButton10 = new javax.swing.JButton();
        jbMButton11 = new javax.swing.JButton();
        jbMButton12 = new javax.swing.JButton();
        jbMButton13 = new javax.swing.JButton();
        jbMButton14 = new javax.swing.JButton();
        jbMButton15 = new javax.swing.JButton();
        jbMButton16 = new javax.swing.JButton();
        jbMButton17 = new javax.swing.JButton();
        jbMButton18 = new javax.swing.JButton();
        jbMButton19 = new javax.swing.JButton();
        jbMButton20 = new javax.swing.JButton();
        jbMButton21 = new javax.swing.JButton();
        jbMButton22 = new javax.swing.JButton();
        jbMButton23 = new javax.swing.JButton();
        jbMButton24 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 255));

        jpMTitle.setBackground(new java.awt.Color(204, 255, 255));
        jpMTitle.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 2, true));

        jlMTitle.setBackground(new java.awt.Color(204, 255, 255));
        jlMTitle.setFont(new java.awt.Font("Berlin Sans FB", 0, 36)); // NOI18N
        jlMTitle.setForeground(new java.awt.Color(0, 153, 153));
        jlMTitle.setText("MEMORY");

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setText("Player");

        jlP1Name.setText("Player 1:");

        jlP2Name.setText("Player 2:");

        jLabel4.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 153));
        jLabel4.setText("Matches");

        jlP1Matches.setText("0");

        jlP2Matches.setText("0");

        jLabel7.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 153, 153));
        jLabel7.setText("Wins");

        jlP1Wins.setText("0");

        jlP2Wins.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jlP1Name)
                    .addComponent(jlP2Name))
                .addGap(68, 68, 68)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jlP1Matches)
                    .addComponent(jlP2Matches))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlP2Wins)
                    .addComponent(jlP1Wins)
                    .addComponent(jLabel7))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlP1Name)
                    .addComponent(jlP1Matches)
                    .addComponent(jlP1Wins))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlP2Name)
                    .addComponent(jlP2Matches)
                    .addComponent(jlP2Wins))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpMTitleLayout = new javax.swing.GroupLayout(jpMTitle);
        jpMTitle.setLayout(jpMTitleLayout);
        jpMTitleLayout.setHorizontalGroup(
            jpMTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMTitleLayout.createSequentialGroup()
                .addGap(379, 379, 379)
                .addComponent(jlMTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jpMTitleLayout.setVerticalGroup(
            jpMTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMTitleLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jpMTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlMTitle))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpMGameArea.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 153, 153)));
        jpMGameArea.setLayout(new java.awt.GridLayout(4, 6, 10, 10));

        jbMButton1.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 36)); // NOI18N
        jbMButton1.setForeground(new java.awt.Color(0, 153, 153));
        jbMButton1.setText("1");
        jpMGameArea.add(jbMButton1);

        jbMButton2.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 36)); // NOI18N
        jbMButton2.setForeground(new java.awt.Color(0, 153, 153));
        jbMButton2.setText("2");
        jpMGameArea.add(jbMButton2);

        jbMButton3.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 36)); // NOI18N
        jbMButton3.setForeground(new java.awt.Color(0, 153, 153));
        jbMButton3.setText("3");
        jbMButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbMButton3ActionPerformed(evt);
            }
        });
        jpMGameArea.add(jbMButton3);

        jbMButton4.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 36)); // NOI18N
        jbMButton4.setForeground(new java.awt.Color(0, 153, 153));
        jbMButton4.setText("4");
        jpMGameArea.add(jbMButton4);

        jbMButton5.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 36)); // NOI18N
        jbMButton5.setForeground(new java.awt.Color(0, 153, 153));
        jbMButton5.setText("5");
        jpMGameArea.add(jbMButton5);

        jbMButton6.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 36)); // NOI18N
        jbMButton6.setForeground(new java.awt.Color(0, 153, 153));
        jbMButton6.setText("6");
        jbMButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbMButton6ActionPerformed(evt);
            }
        });
        jpMGameArea.add(jbMButton6);

        jbMButton7.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 36)); // NOI18N
        jbMButton7.setForeground(new java.awt.Color(0, 153, 153));
        jbMButton7.setText("7");
        jpMGameArea.add(jbMButton7);

        jbMButton8.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 36)); // NOI18N
        jbMButton8.setForeground(new java.awt.Color(0, 153, 153));
        jbMButton8.setText("8");
        jpMGameArea.add(jbMButton8);

        jbMButton9.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 36)); // NOI18N
        jbMButton9.setForeground(new java.awt.Color(0, 153, 153));
        jbMButton9.setText("9");
        jpMGameArea.add(jbMButton9);

        jbMButton10.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 36)); // NOI18N
        jbMButton10.setForeground(new java.awt.Color(0, 153, 153));
        jbMButton10.setText("10");
        jpMGameArea.add(jbMButton10);

        jbMButton11.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 36)); // NOI18N
        jbMButton11.setForeground(new java.awt.Color(0, 153, 153));
        jbMButton11.setText("11");
        jpMGameArea.add(jbMButton11);

        jbMButton12.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 36)); // NOI18N
        jbMButton12.setForeground(new java.awt.Color(0, 153, 153));
        jbMButton12.setText("12");
        jpMGameArea.add(jbMButton12);

        jbMButton13.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 36)); // NOI18N
        jbMButton13.setForeground(new java.awt.Color(0, 153, 153));
        jbMButton13.setText("13");
        jpMGameArea.add(jbMButton13);

        jbMButton14.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 36)); // NOI18N
        jbMButton14.setForeground(new java.awt.Color(0, 153, 153));
        jbMButton14.setText("14");
        jpMGameArea.add(jbMButton14);

        jbMButton15.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 36)); // NOI18N
        jbMButton15.setForeground(new java.awt.Color(0, 153, 153));
        jbMButton15.setText("15");
        jpMGameArea.add(jbMButton15);

        jbMButton16.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 36)); // NOI18N
        jbMButton16.setForeground(new java.awt.Color(0, 153, 153));
        jbMButton16.setText("16");
        jpMGameArea.add(jbMButton16);

        jbMButton17.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 36)); // NOI18N
        jbMButton17.setForeground(new java.awt.Color(0, 153, 153));
        jbMButton17.setText("17");
        jpMGameArea.add(jbMButton17);

        jbMButton18.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 36)); // NOI18N
        jbMButton18.setForeground(new java.awt.Color(0, 153, 153));
        jbMButton18.setText("18");
        jpMGameArea.add(jbMButton18);

        jbMButton19.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 36)); // NOI18N
        jbMButton19.setForeground(new java.awt.Color(0, 153, 153));
        jbMButton19.setText("19");
        jpMGameArea.add(jbMButton19);

        jbMButton20.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 36)); // NOI18N
        jbMButton20.setForeground(new java.awt.Color(0, 153, 153));
        jbMButton20.setText("20");
        jbMButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbMButton20ActionPerformed(evt);
            }
        });
        jpMGameArea.add(jbMButton20);

        jbMButton21.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 36)); // NOI18N
        jbMButton21.setForeground(new java.awt.Color(0, 153, 153));
        jbMButton21.setText("21");
        jpMGameArea.add(jbMButton21);

        jbMButton22.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 36)); // NOI18N
        jbMButton22.setForeground(new java.awt.Color(0, 153, 153));
        jbMButton22.setText("22");
        jpMGameArea.add(jbMButton22);

        jbMButton23.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 36)); // NOI18N
        jbMButton23.setForeground(new java.awt.Color(0, 153, 153));
        jbMButton23.setText("23");
        jpMGameArea.add(jbMButton23);

        jbMButton24.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 36)); // NOI18N
        jbMButton24.setForeground(new java.awt.Color(0, 153, 153));
        jbMButton24.setText("24");
        jpMGameArea.add(jbMButton24);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpMTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpMGameArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jpMTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpMGameArea, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE)
                .addGap(123, 123, 123))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbMButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbMButton3ActionPerformed

    private void jbMButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbMButton6ActionPerformed

    private void jbMButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMButton20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbMButton20ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbMButton1;
    private javax.swing.JButton jbMButton10;
    private javax.swing.JButton jbMButton11;
    private javax.swing.JButton jbMButton12;
    private javax.swing.JButton jbMButton13;
    private javax.swing.JButton jbMButton14;
    private javax.swing.JButton jbMButton15;
    private javax.swing.JButton jbMButton16;
    private javax.swing.JButton jbMButton17;
    private javax.swing.JButton jbMButton18;
    private javax.swing.JButton jbMButton19;
    private javax.swing.JButton jbMButton2;
    private javax.swing.JButton jbMButton20;
    private javax.swing.JButton jbMButton21;
    private javax.swing.JButton jbMButton22;
    private javax.swing.JButton jbMButton23;
    private javax.swing.JButton jbMButton24;
    private javax.swing.JButton jbMButton3;
    private javax.swing.JButton jbMButton4;
    private javax.swing.JButton jbMButton5;
    private javax.swing.JButton jbMButton6;
    private javax.swing.JButton jbMButton7;
    private javax.swing.JButton jbMButton8;
    private javax.swing.JButton jbMButton9;
    private javax.swing.JLabel jlMTitle;
    private javax.swing.JLabel jlP1Matches;
    private javax.swing.JLabel jlP1Name;
    private javax.swing.JLabel jlP1Wins;
    private javax.swing.JLabel jlP2Matches;
    private javax.swing.JLabel jlP2Name;
    private javax.swing.JLabel jlP2Wins;
    private javax.swing.JPanel jpMGameArea;
    private javax.swing.JPanel jpMTitle;
    // End of variables declaration//GEN-END:variables
}
