/*-
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package citbyui.cit260.sarahjanis.memory.frames;

import citbyui.cit260.sarahjanis.memory.controls.Game;
import citbyui.cit260.sarahjanis.memory.exceptions.BoardException;
import citbyui.cit260.sarahjanis.memory.exceptions.CardException;
import citbyui.cit260.sarahjanis.memory.exceptions.MemoryException;
import citbyui.cit260.sarahjanis.memory.models.Board;
import citbyui.cit260.sarahjanis.memory.models.Card;
import citbyui.cit260.sarahjanis.memory.models.Player;
import citbyui.cit260.sarahjanis.memory.models.SymbolArray;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.awt.*;
import java.awt.event.*;
import javax.swing.*;

/**
 *
 * @author Janis
 */
public class BoardLargeFrame extends javax.swing.JFrame {
     private char symbols[];
     private int indexTurn[] = new int[2];
    Game game;
    Board board;
    SymbolArray symArr;
    Player P1;
    Player P2;
    Card card1;
    Card card2;
    boolean matched = false;
    //BoardLargeFrame lFrame;
    private int tCounter=1;
    private int CLICKS;
    private int matchedGame;
    /**
     * Creates new form BoardLargeFrame
     */
    public BoardLargeFrame(Player player1, Player player2, Board setBoard, char getSymbols[]) {
        P1 = player1;
        P2 = player2;
        board = setBoard;
        initComponents();
        setLocationRelativeTo(null);
        symbols = getSymbols;
        matchedGame = 0;
        CLICKS = 0;
        
        jlP1Name.setText(P1.getName());
        jlP2Name.setText(P2.getName());
        
        jlInstructions.setText(P1.getName() + ": Choose a card.");        
        jbNext.setVisible(false);
                  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpMTitle = new javax.swing.JPanel();
        jlMTitle = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jlP1Name = new javax.swing.JLabel();
        jlP2Name = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jlP1Matches = new javax.swing.JLabel();
        jlP2Matches = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jbHelp = new javax.swing.JButton();
        jbQuit = new javax.swing.JButton();
        jbMainMenu = new javax.swing.JButton();
        jpGamePlayInstructions = new javax.swing.JPanel();
        jlFirstTurn = new javax.swing.JLabel();
        jlInstructions = new javax.swing.JLabel();
        jbNext = new javax.swing.JButton();
        jpMGameArea = new javax.swing.JPanel();
        jb1 = new javax.swing.JButton();
        jb2 = new javax.swing.JButton();
        jb3 = new javax.swing.JButton();
        jb4 = new javax.swing.JButton();
        jb5 = new javax.swing.JButton();
        jb6 = new javax.swing.JButton();
        jb7 = new javax.swing.JButton();
        jb8 = new javax.swing.JButton();
        jb9 = new javax.swing.JButton();
        jb10 = new javax.swing.JButton();
        jb11 = new javax.swing.JButton();
        jb12 = new javax.swing.JButton();
        jb13 = new javax.swing.JButton();
        jb14 = new javax.swing.JButton();
        jb15 = new javax.swing.JButton();
        jb16 = new javax.swing.JButton();
        jb17 = new javax.swing.JButton();
        jb18 = new javax.swing.JButton();
        jb19 = new javax.swing.JButton();
        jb20 = new javax.swing.JButton();
        jb21 = new javax.swing.JButton();
        jb22 = new javax.swing.JButton();
        jb23 = new javax.swing.JButton();
        jb24 = new javax.swing.JButton();
        jb25 = new javax.swing.JButton();
        jb26 = new javax.swing.JButton();
        jb27 = new javax.swing.JButton();
        jb28 = new javax.swing.JButton();
        jb29 = new javax.swing.JButton();
        jb30 = new javax.swing.JButton();
        jb31 = new javax.swing.JButton();
        jb32 = new javax.swing.JButton();
        jb33 = new javax.swing.JButton();
        jb34 = new javax.swing.JButton();
        jb35 = new javax.swing.JButton();
        jb36 = new javax.swing.JButton();
        jb37 = new javax.swing.JButton();
        jb38 = new javax.swing.JButton();
        jb39 = new javax.swing.JButton();
        jb40 = new javax.swing.JButton();
        jb41 = new javax.swing.JButton();
        jb42 = new javax.swing.JButton();
        jb43 = new javax.swing.JButton();
        jb44 = new javax.swing.JButton();
        jb45 = new javax.swing.JButton();
        jb46 = new javax.swing.JButton();
        jb47 = new javax.swing.JButton();
        jb48 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpMTitle.setBackground(new java.awt.Color(204, 255, 255));
        jpMTitle.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 2, true));

        jlMTitle.setBackground(new java.awt.Color(204, 255, 255));
        jlMTitle.setFont(new java.awt.Font("Berlin Sans FB", 0, 36)); // NOI18N
        jlMTitle.setForeground(new java.awt.Color(0, 153, 153));
        jlMTitle.setText("MEMORY");

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setText("Player");

        jlP1Name.setText("Player 1:");

        jlP2Name.setText("Player 2:");

        jLabel4.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 153));
        jLabel4.setText("Matches");

        jlP1Matches.setText("0");

        jlP2Matches.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jlP1Name, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                            .addComponent(jlP2Name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jlP1Matches, javax.swing.GroupLayout.DEFAULT_SIZE, 14, Short.MAX_VALUE)
                            .addComponent(jlP2Matches, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(58, 58, 58))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addGap(34, 34, 34))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlP1Name)
                    .addComponent(jlP1Matches))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlP2Name)
                    .addComponent(jlP2Matches))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));

        jbHelp.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jbHelp.setForeground(new java.awt.Color(0, 153, 153));
        jbHelp.setText("HELP");
        jbHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbHelpActionPerformed(evt);
            }
        });

        jbQuit.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jbQuit.setForeground(new java.awt.Color(0, 153, 153));
        jbQuit.setText("QUIT");
        jbQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbQuitActionPerformed(evt);
            }
        });

        jbMainMenu.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jbMainMenu.setForeground(new java.awt.Color(0, 153, 153));
        jbMainMenu.setText("MAIN MENU");
        jbMainMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbMainMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbQuit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbHelp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbMainMenu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jbMainMenu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbHelp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbQuit)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jpGamePlayInstructions.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout jpGamePlayInstructionsLayout = new javax.swing.GroupLayout(jpGamePlayInstructions);
        jpGamePlayInstructions.setLayout(jpGamePlayInstructionsLayout);
        jpGamePlayInstructionsLayout.setHorizontalGroup(
            jpGamePlayInstructionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpGamePlayInstructionsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlInstructions, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlFirstTurn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpGamePlayInstructionsLayout.setVerticalGroup(
            jpGamePlayInstructionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpGamePlayInstructionsLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jlFirstTurn)
                .addContainerGap())
            .addComponent(jlInstructions, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jbNext.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jbNext.setForeground(new java.awt.Color(0, 153, 153));
        jbNext.setText("NEXT");
        jbNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpMTitleLayout = new javax.swing.GroupLayout(jpMTitle);
        jpMTitle.setLayout(jpMTitleLayout);
        jpMTitleLayout.setHorizontalGroup(
            jpMTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMTitleLayout.createSequentialGroup()
                .addGroup(jpMTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpMTitleLayout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(jlMTitle))
                    .addGroup(jpMTitleLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jpGamePlayInstructions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbNext)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 136, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        jpMTitleLayout.setVerticalGroup(
            jpMTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpMTitleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpMTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpMTitleLayout.createSequentialGroup()
                        .addGroup(jpMTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlMTitle)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jpMTitleLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jpMTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jbNext)
                            .addComponent(jpGamePlayInstructions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        jpMGameArea.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 153, 153)));
        jpMGameArea.setLayout(new java.awt.GridLayout(6, 8, 10, 10));

        jb1.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 36)); // NOI18N
        jb1.setForeground(new java.awt.Color(0, 153, 153));
        jb1.setText("1");
        jb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb1ActionPerformed(evt);
            }
        });
        jpMGameArea.add(jb1);

        jb2.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 36)); // NOI18N
        jb2.setForeground(new java.awt.Color(0, 153, 153));
        jb2.setText("2");
        jb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb2ActionPerformed(evt);
            }
        });
        jpMGameArea.add(jb2);

        jb3.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 36)); // NOI18N
        jb3.setForeground(new java.awt.Color(0, 153, 153));
        jb3.setText("3");
        jb3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb3ActionPerformed(evt);
            }
        });
        jpMGameArea.add(jb3);

        jb4.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 36)); // NOI18N
        jb4.setForeground(new java.awt.Color(0, 153, 153));
        jb4.setText("4");
        jb4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb4ActionPerformed(evt);
            }
        });
        jpMGameArea.add(jb4);

        jb5.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 36)); // NOI18N
        jb5.setForeground(new java.awt.Color(0, 153, 153));
        jb5.setText("5");
        jb5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb5ActionPerformed(evt);
            }
        });
        jpMGameArea.add(jb5);

        jb6.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 36)); // NOI18N
        jb6.setForeground(new java.awt.Color(0, 153, 153));
        jb6.setText("6");
        jb6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb6ActionPerformed(evt);
            }
        });
        jpMGameArea.add(jb6);

        jb7.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 36)); // NOI18N
        jb7.setForeground(new java.awt.Color(0, 153, 153));
        jb7.setText("7");
        jb7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb7ActionPerformed(evt);
            }
        });
        jpMGameArea.add(jb7);

        jb8.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 36)); // NOI18N
        jb8.setForeground(new java.awt.Color(0, 153, 153));
        jb8.setText("8");
        jb8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb8ActionPerformed(evt);
            }
        });
        jpMGameArea.add(jb8);

        jb9.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 36)); // NOI18N
        jb9.setForeground(new java.awt.Color(0, 153, 153));
        jb9.setText("9");
        jb9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb9ActionPerformed(evt);
            }
        });
        jpMGameArea.add(jb9);

        jb10.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 36)); // NOI18N
        jb10.setForeground(new java.awt.Color(0, 153, 153));
        jb10.setText("10");
        jb10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb10ActionPerformed(evt);
            }
        });
        jpMGameArea.add(jb10);

        jb11.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 36)); // NOI18N
        jb11.setForeground(new java.awt.Color(0, 153, 153));
        jb11.setText("11");
        jb11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb11ActionPerformed(evt);
            }
        });
        jpMGameArea.add(jb11);

        jb12.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 36)); // NOI18N
        jb12.setForeground(new java.awt.Color(0, 153, 153));
        jb12.setText("12");
        jb12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb12ActionPerformed(evt);
            }
        });
        jpMGameArea.add(jb12);

        jb13.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 36)); // NOI18N
        jb13.setForeground(new java.awt.Color(0, 153, 153));
        jb13.setText("13");
        jb13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb13ActionPerformed(evt);
            }
        });
        jpMGameArea.add(jb13);

        jb14.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 36)); // NOI18N
        jb14.setForeground(new java.awt.Color(0, 153, 153));
        jb14.setText("14");
        jb14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb14ActionPerformed(evt);
            }
        });
        jpMGameArea.add(jb14);

        jb15.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 36)); // NOI18N
        jb15.setForeground(new java.awt.Color(0, 153, 153));
        jb15.setText("15");
        jb15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb15ActionPerformed(evt);
            }
        });
        jpMGameArea.add(jb15);

        jb16.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 36)); // NOI18N
        jb16.setForeground(new java.awt.Color(0, 153, 153));
        jb16.setText("16");
        jb16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb16ActionPerformed(evt);
            }
        });
        jpMGameArea.add(jb16);

        jb17.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 36)); // NOI18N
        jb17.setForeground(new java.awt.Color(0, 153, 153));
        jb17.setText("17");
        jb17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb17ActionPerformed(evt);
            }
        });
        jpMGameArea.add(jb17);

        jb18.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 36)); // NOI18N
        jb18.setForeground(new java.awt.Color(0, 153, 153));
        jb18.setText("18");
        jb18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb18ActionPerformed(evt);
            }
        });
        jpMGameArea.add(jb18);

        jb19.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 36)); // NOI18N
        jb19.setForeground(new java.awt.Color(0, 153, 153));
        jb19.setText("19");
        jb19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb19ActionPerformed(evt);
            }
        });
        jpMGameArea.add(jb19);

        jb20.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 36)); // NOI18N
        jb20.setForeground(new java.awt.Color(0, 153, 153));
        jb20.setText("20");
        jb20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb20ActionPerformed(evt);
            }
        });
        jpMGameArea.add(jb20);

        jb21.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 36)); // NOI18N
        jb21.setForeground(new java.awt.Color(0, 153, 153));
        jb21.setText("21");
        jb21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb21ActionPerformed(evt);
            }
        });
        jpMGameArea.add(jb21);

        jb22.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 36)); // NOI18N
        jb22.setForeground(new java.awt.Color(0, 153, 153));
        jb22.setText("22");
        jb22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb22ActionPerformed(evt);
            }
        });
        jpMGameArea.add(jb22);

        jb23.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 36)); // NOI18N
        jb23.setForeground(new java.awt.Color(0, 153, 153));
        jb23.setText("23");
        jb23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb23ActionPerformed(evt);
            }
        });
        jpMGameArea.add(jb23);

        jb24.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 36)); // NOI18N
        jb24.setForeground(new java.awt.Color(0, 153, 153));
        jb24.setText("24");
        jb24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb24ActionPerformed(evt);
            }
        });
        jpMGameArea.add(jb24);

        jb25.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 36)); // NOI18N
        jb25.setForeground(new java.awt.Color(0, 153, 153));
        jb25.setText("25");
        jb25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb25ActionPerformed(evt);
            }
        });
        jpMGameArea.add(jb25);

        jb26.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 36)); // NOI18N
        jb26.setForeground(new java.awt.Color(0, 153, 153));
        jb26.setText("26");
        jb26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb26ActionPerformed(evt);
            }
        });
        jpMGameArea.add(jb26);

        jb27.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 36)); // NOI18N
        jb27.setForeground(new java.awt.Color(0, 153, 153));
        jb27.setText("27");
        jb27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb27ActionPerformed(evt);
            }
        });
        jpMGameArea.add(jb27);

        jb28.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 36)); // NOI18N
        jb28.setForeground(new java.awt.Color(0, 153, 153));
        jb28.setText("28");
        jb28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb28ActionPerformed(evt);
            }
        });
        jpMGameArea.add(jb28);

        jb29.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 36)); // NOI18N
        jb29.setForeground(new java.awt.Color(0, 153, 153));
        jb29.setText("29");
        jb29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb29ActionPerformed(evt);
            }
        });
        jpMGameArea.add(jb29);

        jb30.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 36)); // NOI18N
        jb30.setForeground(new java.awt.Color(0, 153, 153));
        jb30.setText("30");
        jb30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb30ActionPerformed(evt);
            }
        });
        jpMGameArea.add(jb30);

        jb31.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 36)); // NOI18N
        jb31.setForeground(new java.awt.Color(0, 153, 153));
        jb31.setText("31");
        jb31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb31ActionPerformed(evt);
            }
        });
        jpMGameArea.add(jb31);

        jb32.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 36)); // NOI18N
        jb32.setForeground(new java.awt.Color(0, 153, 153));
        jb32.setText("32");
        jb32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb32ActionPerformed(evt);
            }
        });
        jpMGameArea.add(jb32);

        jb33.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 36)); // NOI18N
        jb33.setForeground(new java.awt.Color(0, 153, 153));
        jb33.setText("33");
        jb33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb33ActionPerformed(evt);
            }
        });
        jpMGameArea.add(jb33);

        jb34.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 36)); // NOI18N
        jb34.setForeground(new java.awt.Color(0, 153, 153));
        jb34.setText("34");
        jb34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb34ActionPerformed(evt);
            }
        });
        jpMGameArea.add(jb34);

        jb35.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 36)); // NOI18N
        jb35.setForeground(new java.awt.Color(0, 153, 153));
        jb35.setText("35");
        jb35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb35ActionPerformed(evt);
            }
        });
        jpMGameArea.add(jb35);

        jb36.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 36)); // NOI18N
        jb36.setForeground(new java.awt.Color(0, 153, 153));
        jb36.setText("36");
        jb36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb36ActionPerformed(evt);
            }
        });
        jpMGameArea.add(jb36);

        jb37.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 36)); // NOI18N
        jb37.setForeground(new java.awt.Color(0, 153, 153));
        jb37.setText("37");
        jb37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb37ActionPerformed(evt);
            }
        });
        jpMGameArea.add(jb37);

        jb38.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 36)); // NOI18N
        jb38.setForeground(new java.awt.Color(0, 153, 153));
        jb38.setText("38");
        jb38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb38ActionPerformed(evt);
            }
        });
        jpMGameArea.add(jb38);

        jb39.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 36)); // NOI18N
        jb39.setForeground(new java.awt.Color(0, 153, 153));
        jb39.setText("39");
        jb39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb39ActionPerformed(evt);
            }
        });
        jpMGameArea.add(jb39);

        jb40.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 36)); // NOI18N
        jb40.setForeground(new java.awt.Color(0, 153, 153));
        jb40.setText("40");
        jb40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb40ActionPerformed(evt);
            }
        });
        jpMGameArea.add(jb40);

        jb41.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 36)); // NOI18N
        jb41.setForeground(new java.awt.Color(0, 153, 153));
        jb41.setText("41");
        jb41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb41ActionPerformed(evt);
            }
        });
        jpMGameArea.add(jb41);

        jb42.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 36)); // NOI18N
        jb42.setForeground(new java.awt.Color(0, 153, 153));
        jb42.setText("42");
        jb42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb42ActionPerformed(evt);
            }
        });
        jpMGameArea.add(jb42);

        jb43.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 36)); // NOI18N
        jb43.setForeground(new java.awt.Color(0, 153, 153));
        jb43.setText("43");
        jb43.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb43ActionPerformed(evt);
            }
        });
        jpMGameArea.add(jb43);

        jb44.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 36)); // NOI18N
        jb44.setForeground(new java.awt.Color(0, 153, 153));
        jb44.setText("44");
        jb44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb44ActionPerformed(evt);
            }
        });
        jpMGameArea.add(jb44);

        jb45.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 36)); // NOI18N
        jb45.setForeground(new java.awt.Color(0, 153, 153));
        jb45.setText("45");
        jb45.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb45ActionPerformed(evt);
            }
        });
        jpMGameArea.add(jb45);

        jb46.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 36)); // NOI18N
        jb46.setForeground(new java.awt.Color(0, 153, 153));
        jb46.setText("46");
        jb46.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb46ActionPerformed(evt);
            }
        });
        jpMGameArea.add(jb46);

        jb47.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 36)); // NOI18N
        jb47.setForeground(new java.awt.Color(0, 153, 153));
        jb47.setText("47");
        jb47.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb47ActionPerformed(evt);
            }
        });
        jpMGameArea.add(jb47);

        jb48.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 36)); // NOI18N
        jb48.setForeground(new java.awt.Color(0, 153, 153));
        jb48.setText("48");
        jb48.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb48ActionPerformed(evt);
            }
        });
        jpMGameArea.add(jb48);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpMTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpMGameArea, javax.swing.GroupLayout.DEFAULT_SIZE, 1061, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpMTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpMGameArea, javax.swing.GroupLayout.DEFAULT_SIZE, 521, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbMainMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMainMenuActionPerformed
        this.dispose();
        MainFrame mainFrame =  new MainFrame();
        mainFrame.setVisible(true);
    }//GEN-LAST:event_jbMainMenuActionPerformed

    private void jbHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbHelpActionPerformed
        HelpFrame helpFrame = new HelpFrame();
        helpFrame.setVisible(true);
    }//GEN-LAST:event_jbHelpActionPerformed

    private void jbQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbQuitActionPerformed
        this.dispose();
    }//GEN-LAST:event_jbQuitActionPerformed
    
    private void jb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb1ActionPerformed
        String symbol = Character.toString(symbols[0]); // index should be button#-1
        jb1.setText(symbol);
        jb1.setEnabled(false);
        CLICKS++;
       
        setIndices(1); //save the index of this card to an array
        afterClick();
            
    }//GEN-LAST:event_jb1ActionPerformed
    private void setIndices(int index){
        
        if (CLICKS == 1){
            indexTurn[0]= index;
            
        }
        else if (CLICKS ==2){
          indexTurn[1]= index;
        }
      
    }
    
    private boolean checkMatch(){
        
        if (symbols[indexTurn[0]-1]== symbols[indexTurn[1]-1]){
            matchedGame++;
            return true;
        }
        else
            return false;
    }
    private void afterClick(/*JButton button*/){
        if (CLICKS == 2){
            matched = checkMatch();
            CLICKS =0;
            
            if (tCounter % 2 != 0){
                if (matched == true){
                     P1.setMatches(P1.getMatches()+1);
                     jlInstructions.setText(P1.getName() + ": Yay, you made a match! You get another turn.");
                     jlP1Matches.setText(Integer.toString(P1.getMatches()));
                     jbNext.setVisible(true);
                        disableCards(/*button*/);
            
                    }
                else {
                    jlInstructions.setText(P1.getName() + ": Sorry, not a match. Next player's turn.");
                    jbNext.setVisible(true);
                        disableCards(/*button*/);
            
                    //next player's turn
                    tCounter++;} 
        }
             
            else {
                if (matched == true){
                     P2.setMatches(P2.getMatches()+1);
                     jlInstructions.setText(P2.getName() + ": Yay, you made a match! You get another turn.");
                     jlP2Matches.setText(Integer.toString(P2.getMatches()));
                    jbNext.setVisible(true);
                        disableCards(/*button*/);
            
                    }
                else{
                    jlInstructions.setText(P2.getName() + ": Sorry, not a match. Next player's turn.");
                    jbNext.setVisible(true);
                        disableCards(/*button*/);
            
                    //next player's turn
                    tCounter++;} 
            }
        }
        else{
            if (tCounter % 2 != 0){
              jlInstructions.setText(P1.getName() + ": Choose another card.");  
            }
            else{
              jlInstructions.setText(P2.getName() + ": Choose another card.");
            }
        }
            
    }
    private void setBoard(){
        //make this fix cards somehow
        if (matched == false){
            if (indexTurn[0]==1 || indexTurn[1]==1){
               jb1.setText("1"); 
            }
            if (indexTurn[0]==2 || indexTurn[1]==2){
               jb2.setText("2"); 
            }
            if (indexTurn[0]==3 || indexTurn[1]==3){
               jb3.setText("3"); 
            }
            if (indexTurn[0]==4 || indexTurn[1]==4){
               jb4.setText("4"); 
            }
            if (indexTurn[0]==5 || indexTurn[1]==5){
               jb5.setText("5"); 
            }
            if (indexTurn[0]==6 || indexTurn[1]==6){
               jb6.setText("6"); 
            }
            if (indexTurn[0]==7 || indexTurn[1]==7){
               jb7.setText("7"); 
            }
            if (indexTurn[0]==8 || indexTurn[1]==8){
               jb8.setText("8"); 
            }
            if (indexTurn[0]==9 || indexTurn[1]==9){
               jb9.setText("9"); 
            }
            if (indexTurn[0]==10 || indexTurn[1]==10){
               jb10.setText("10"); 
            }
            if (indexTurn[0]==11 || indexTurn[1]==11){
               jb11.setText("11"); 
            }
            if (indexTurn[0]==12 || indexTurn[1]==12){
               jb12.setText("12"); 
            }
            if (indexTurn[0]==13 || indexTurn[1]==13){
               jb13.setText("13"); 
            }
            if (indexTurn[0]==14 || indexTurn[1]==14){
               jb14.setText("14"); 
            }
            if (indexTurn[0]==15 || indexTurn[1]==15){
               jb15.setText("15"); 
            }
            if (indexTurn[0]==16 || indexTurn[1]==16){
               jb16.setText("16"); 
            }
            if (indexTurn[0]==17 || indexTurn[1]==17){
               jb17.setText("17"); 
            }
            if (indexTurn[0]==18 || indexTurn[1]==18){
               jb18.setText("18"); 
            }
            if (indexTurn[0]==19 || indexTurn[1]==19){
               jb19.setText("19"); 
            }
            if (indexTurn[0]==20 || indexTurn[1]==20){
               jb20.setText("20"); 
            }
            if (indexTurn[0]==21 || indexTurn[1]==21){
               jb21.setText("21"); 
            }
            if (indexTurn[0]==22 || indexTurn[1]==22){
               jb22.setText("22"); 
            }
            if (indexTurn[0]==23 || indexTurn[1]==23){
               jb23.setText("23"); 
            }
            if (indexTurn[0]==24 || indexTurn[1]==24){
               jb24.setText("24"); 
            }
            if (indexTurn[0]==25 || indexTurn[1]==25){
               jb25.setText("25"); 
            }
            if (indexTurn[0]==26 || indexTurn[1]==26){
               jb26.setText("26"); 
            }
            if (indexTurn[0]==27 || indexTurn[1]==27){
               jb27.setText("27"); 
            }
            if (indexTurn[0]==28 || indexTurn[1]==28){
               jb28.setText("28"); 
            }
            if (indexTurn[0]==29 || indexTurn[1]==29){
               jb29.setText("29"); 
            }
            if (indexTurn[0]==30 || indexTurn[1]==30){
               jb30.setText("30"); 
            }
            if (indexTurn[0]==31 || indexTurn[1]==31){
               jb31.setText("31"); 
            }
            if (indexTurn[0]==32 || indexTurn[1]==32){
               jb32.setText("32"); 
            }
            if (indexTurn[0]==33 || indexTurn[1]==33){
               jb33.setText("33"); 
            }
            if (indexTurn[0]==34 || indexTurn[1]==34){
               jb34.setText("34"); 
            }
            if (indexTurn[0]==35 || indexTurn[1]==35){
               jb35.setText("35"); 
            }
            if (indexTurn[0]==36 || indexTurn[1]==36){
               jb36.setText("36"); 
            }
            if (indexTurn[0]==37 || indexTurn[1]==37){
               jb37.setText("37"); 
            }
            if (indexTurn[0]==38 || indexTurn[1]==38){
               jb38.setText("38"); 
            }
            if (indexTurn[0]==39 || indexTurn[1]==39){
               jb39.setText("39"); 
            }
            if (indexTurn[0]==40 || indexTurn[1]==40){
               jb40.setText("40"); 
            }
            if (indexTurn[0]==41 || indexTurn[1]==41){
               jb41.setText("41"); 
            }
            if (indexTurn[0]==42 || indexTurn[1]==42){
               jb42.setText("42"); 
            }
            if (indexTurn[0]==43 || indexTurn[1]==43){
               jb43.setText("43"); 
            }
            if (indexTurn[0]==44 || indexTurn[1]==44){
               jb44.setText("44"); 
            }
            if (indexTurn[0]==45 || indexTurn[1]==45){
               jb45.setText("45"); 
            }
            if (indexTurn[0]==46 || indexTurn[1]==46){
               jb46.setText("46"); 
            }
            if (indexTurn[0]==47 || indexTurn[1]==47){
               jb47.setText("47"); 
            }
            if (indexTurn[0]==48 || indexTurn[1]==48){
               jb48.setText("48"); 
            }
            
            
            
            matched = false;
            jbNext.setVisible(false); 
                enableCards();
                
                //player instructions
                if (tCounter % 2 != 0){
                    jlInstructions.setText(P1.getName() + ": Choose a card.");  
                    }
                else{
                    jlInstructions.setText(P2.getName() + ": Choose a card.");
                    }
                }
        else if (matched == true){
            if (indexTurn[0]==1 || indexTurn[1]==1){
               jb1.setVisible(false); 
            }
            if (indexTurn[0]==2 || indexTurn[1]==2){
               jb2.setVisible(false); 
            }
            if (indexTurn[0]==3 || indexTurn[1]==3){
               jb3.setVisible(false);
            }
            if (indexTurn[0]==4 || indexTurn[1]==4){
               jb4.setVisible(false); 
            }
            if (indexTurn[0]==5 || indexTurn[1]==5){
               jb5.setVisible(false); 
            }
            if (indexTurn[0]==6 || indexTurn[1]==6){
               jb6.setVisible(false); 
            }
            if (indexTurn[0]==7 || indexTurn[1]==7){
               jb7.setVisible(false); 
            }
            if (indexTurn[0]==8 || indexTurn[1]==8){
               jb8.setVisible(false); 
            }
            if (indexTurn[0]==9 || indexTurn[1]==9){
               jb9.setVisible(false); 
            }
            if (indexTurn[0]==10 || indexTurn[1]==10){
               jb10.setVisible(false); 
            }
            if (indexTurn[0]==11 || indexTurn[1]==11){
               jb11.setVisible(false); 
            }
            if (indexTurn[0]==12 || indexTurn[1]==12){
               jb12.setVisible(false); 
            }
            if (indexTurn[0]==13 || indexTurn[1]==13){
               jb13.setVisible(false); 
            }
            if (indexTurn[0]==14 || indexTurn[1]==14){
               jb14.setVisible(false); 
            }
            if (indexTurn[0]==15 || indexTurn[1]==15){
               jb15.setVisible(false); 
            }
            if (indexTurn[0]==16 || indexTurn[1]==16){
               jb16.setVisible(false); 
            }
            if (indexTurn[0]==17 || indexTurn[1]==17){
               jb17.setVisible(false); 
            }
            if (indexTurn[0]==18 || indexTurn[1]==18){
               jb18.setVisible(false); 
            }
            if (indexTurn[0]==19 || indexTurn[1]==19){
               jb19.setVisible(false); 
            }
            if (indexTurn[0]==20 || indexTurn[1]==20){
               jb20.setVisible(false); 
            }
            if (indexTurn[0]==21 || indexTurn[1]==21){
               jb21.setVisible(false); 
            }
            if (indexTurn[0]==22 || indexTurn[1]==22){
               jb22.setVisible(false); 
            }
            if (indexTurn[0]==23 || indexTurn[1]==23){
               jb23.setVisible(false); 
            }
            if (indexTurn[0]==24 || indexTurn[1]==24){
               jb24.setVisible(false); 
            }
            if (indexTurn[0]==25 || indexTurn[1]==25){
               jb25.setVisible(false); 
            }
            if (indexTurn[0]==26 || indexTurn[1]==26){
               jb26.setVisible(false); 
            }
            if (indexTurn[0]==27 || indexTurn[1]==27){
               jb27.setVisible(false); 
            }
            if (indexTurn[0]==28 || indexTurn[1]==28){
               jb28.setVisible(false); 
            }
            if (indexTurn[0]==29 || indexTurn[1]==29){
               jb29.setVisible(false); 
            }
            if (indexTurn[0]==30 || indexTurn[1]==30){
               jb30.setVisible(false); 
            }
            if (indexTurn[0]==31 || indexTurn[1]==31){
               jb31.setVisible(false); 
            }
            if (indexTurn[0]==32 || indexTurn[1]==32){
               jb32.setVisible(false); 
            }
            if (indexTurn[0]==33 || indexTurn[1]==33){
               jb33.setVisible(false); 
            }
            if (indexTurn[0]==34 || indexTurn[1]==34){
               jb34.setVisible(false); 
            }
            if (indexTurn[0]==35 || indexTurn[1]==35){
               jb35.setVisible(false); 
            }
            if (indexTurn[0]==36 || indexTurn[1]==36){
               jb36.setVisible(false); 
            }
            if (indexTurn[0]==37 || indexTurn[1]==37){
               jb37.setVisible(false); 
            }
            if (indexTurn[0]==38 || indexTurn[1]==38){
               jb38.setVisible(false); 
            }
            if (indexTurn[0]==39 || indexTurn[1]==39){
               jb39.setVisible(false); 
            }
            if (indexTurn[0]==40 || indexTurn[1]==40){
               jb40.setVisible(false); 
            }
            if (indexTurn[0]==41 || indexTurn[1]==41){
               jb41.setVisible(false); 
            }
            if (indexTurn[0]==42 || indexTurn[1]==42){
               jb42.setVisible(false); 
            }
            if (indexTurn[0]==43 || indexTurn[1]==43){
               jb43.setVisible(false); 
            }
            if (indexTurn[0]==44 || indexTurn[1]==44){
               jb44.setVisible(false); 
            }
            if (indexTurn[0]==45 || indexTurn[1]==45){
               jb45.setVisible(false); 
            }
            if (indexTurn[0]==46 || indexTurn[1]==46){
               jb46.setVisible(false); 
            }
            if (indexTurn[0]==47 || indexTurn[1]==47){
               jb47.setVisible(false); 
            }
            if (indexTurn[0]==48 || indexTurn[1]==48){
               jb48.setVisible(false); 
            }
            jbNext.setVisible(false);
                enableCards();
                
                //player instructions
                if (tCounter % 2 != 0){
                    jlInstructions.setText(P1.getName() + ": Choose a card.");  
                    }
                else{
                    jlInstructions.setText(P2.getName() + ": Choose a card.");
                    }
                }
        
    }
  //  private void disableCards(/*JButton button*/){
       // button.setEnabled(false);
   // }
    private void disableCards(){
        jb1.setEnabled(false);
        jb2.setEnabled(false);
        jb3.setEnabled(false);
        jb4.setEnabled(false);
        jb5.setEnabled(false);
        jb6.setEnabled(false);
        jb7.setEnabled(false);
        jb8.setEnabled(false);
        jb9.setEnabled(false);
        jb10.setEnabled(false);
        jb11.setEnabled(false);
        jb12.setEnabled(false);
        jb13.setEnabled(false);
        jb14.setEnabled(false);
        jb15.setEnabled(false);
        jb16.setEnabled(false);
        jb17.setEnabled(false);
        jb18.setEnabled(false);
        jb19.setEnabled(false);
        jb20.setEnabled(false);
        jb21.setEnabled(false);
        jb22.setEnabled(false);
        jb23.setEnabled(false);
        jb24.setEnabled(false);
        jb25.setEnabled(false);
        jb26.setEnabled(false);
        jb27.setEnabled(false);
        jb28.setEnabled(false);
        jb29.setEnabled(false);
        jb30.setEnabled(false);
        jb31.setEnabled(false);
        jb32.setEnabled(false);
        jb33.setEnabled(false);
        jb34.setEnabled(false);
        jb35.setEnabled(false);
        jb36.setEnabled(false);
        jb37.setEnabled(false);
        jb38.setEnabled(false);
        jb39.setEnabled(false);
        jb40.setEnabled(false);
        jb41.setEnabled(false);
        jb42.setEnabled(false);
        jb43.setEnabled(false);
        jb44.setEnabled(false);
        jb44.setEnabled(false);
        jb45.setEnabled(false);
        jb46.setEnabled(false);
        jb47.setEnabled(false);
        jb48.setEnabled(false);
    }
    private void enableCards(){
        jb1.setEnabled(true);
        jb2.setEnabled(true);
        jb3.setEnabled(true);
        jb4.setEnabled(true);
        jb5.setEnabled(true);
        jb6.setEnabled(true);
        jb7.setEnabled(true);
        jb8.setEnabled(true);
        jb9.setEnabled(true);
        jb10.setEnabled(true);
        jb11.setEnabled(true);
        jb12.setEnabled(true);
        jb13.setEnabled(true);
        jb14.setEnabled(true);
        jb15.setEnabled(true);
        jb16.setEnabled(true);
        jb17.setEnabled(true);
        jb18.setEnabled(true);
        jb19.setEnabled(true);
        jb20.setEnabled(true);
        jb21.setEnabled(true);
        jb22.setEnabled(true);
        jb23.setEnabled(true);
        jb24.setEnabled(true);
        jb25.setEnabled(true);
        jb26.setEnabled(true);
        jb27.setEnabled(true);
        jb28.setEnabled(true);
        jb29.setEnabled(true);
        jb30.setEnabled(true);
        jb31.setEnabled(true);
        jb32.setEnabled(true);
        jb33.setEnabled(true);
        jb34.setEnabled(true);
        jb35.setEnabled(true);
        jb36.setEnabled(true);
        jb37.setEnabled(true);
        jb38.setEnabled(true);
        jb39.setEnabled(true);
        jb40.setEnabled(true);
        jb41.setEnabled(true);
        jb42.setEnabled(true);
        jb43.setEnabled(true);
        jb44.setEnabled(true);
        jb45.setEnabled(true);
        jb46.setEnabled(true);
        jb47.setEnabled(true);
        jb48.setEnabled(true);
        
    }
    
    
    private void jb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb2ActionPerformed
        String symbol = Character.toString(symbols[1]); // index should be button#-1
        jb2.setText(symbol);
        jb2.setEnabled(false);
        CLICKS++;
        
        setIndices(2); //save the index of this card to an array
        afterClick();
        
       
    }//GEN-LAST:event_jb2ActionPerformed

    private void jb3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb3ActionPerformed
        String symbol = Character.toString(symbols[2]); // index should be button#-1
        jb3.setText(symbol);
        jb3.setEnabled(false);
        CLICKS++;

        setIndices(3); //save the index of this card to an array
        afterClick();
     
    }//GEN-LAST:event_jb3ActionPerformed

    private void jb4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb4ActionPerformed
        String symbol = Character.toString(symbols[3]); // index should be button#-1
        jb4.setText(symbol);
        jb4.setEnabled(false);
        CLICKS++;

        setIndices(4); //save the index of this card to an array
        afterClick();
     
    }//GEN-LAST:event_jb4ActionPerformed

    private void jb5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb5ActionPerformed
        String symbol = Character.toString(symbols[4]); // index should be button#-1
        jb5.setText(symbol);
        jb5.setEnabled(false);
        CLICKS++;

        setIndices(5); //save the index of this card to an array
        afterClick();
    
    }//GEN-LAST:event_jb5ActionPerformed

    private void jb6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb6ActionPerformed
        String symbol = Character.toString(symbols[5]); // index should be button#-1
        jb6.setText(symbol);
        jb6.setEnabled(false);
        CLICKS++;

        setIndices(6);
        afterClick();//save the index of this card to an array
     
    }//GEN-LAST:event_jb6ActionPerformed

    private void jb7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb7ActionPerformed
        String symbol = Character.toString(symbols[6]); // index should be button#-1
        jb7.setText(symbol);
        jb7.setEnabled(false);
        CLICKS++;

        setIndices(7);
        afterClick();//save the index of this card to an array
       
       
    }//GEN-LAST:event_jb7ActionPerformed

    private void jb8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb8ActionPerformed
        String symbol = Character.toString(symbols[7]); // index should be button#-1
        jb8.setText(symbol);
        jb8.setEnabled(false);
        CLICKS++;
        
        setIndices(8); //save the index of this card to an array
        afterClick();
     
    }//GEN-LAST:event_jb8ActionPerformed

    private void jb9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb9ActionPerformed
        String symbol = Character.toString(symbols[8]); // index should be button#-1
        jb9.setText(symbol);
        jb9.setEnabled(false);
        CLICKS++;
        
        setIndices(9); //save the index of this card to an array
        afterClick();
    }//GEN-LAST:event_jb9ActionPerformed

    private void jb10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb10ActionPerformed
        String symbol = Character.toString(symbols[9]); // index should be button#-1
        jb10.setText(symbol);
        jb10.setEnabled(false);
        CLICKS++;
        
        setIndices(10); //save the index of this card to an array
        afterClick();
    }//GEN-LAST:event_jb10ActionPerformed

    private void jb11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb11ActionPerformed
        String symbol = Character.toString(symbols[10]); // index should be button#-1
        jb11.setText(symbol);
        jb11.setEnabled(false);
        CLICKS++;
        
        setIndices(11); //save the index of this card to an array
        afterClick();
    }//GEN-LAST:event_jb11ActionPerformed

    private void jb12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb12ActionPerformed
        String symbol = Character.toString(symbols[11]); // index should be button#-1
        jb12.setText(symbol);
        jb12.setEnabled(false);
        CLICKS++;
        
        setIndices(12); //save the index of this card to an array
        afterClick();
    }//GEN-LAST:event_jb12ActionPerformed

    private void jb13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb13ActionPerformed
        String symbol = Character.toString(symbols[12]); // index should be button#-1
        jb13.setText(symbol);
        jb13.setEnabled(false);
        CLICKS++;
        
        setIndices(13); //save the index of this card to an array
        afterClick();
    }//GEN-LAST:event_jb13ActionPerformed

    private void jb14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb14ActionPerformed
        String symbol = Character.toString(symbols[13]); // index should be button#-1
        jb14.setText(symbol);
        jb14.setEnabled(false);
        CLICKS++;
        
        setIndices(14); //save the index of this card to an array
        afterClick();
    }//GEN-LAST:event_jb14ActionPerformed

    private void jb15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb15ActionPerformed
        String symbol = Character.toString(symbols[14]); // index should be button#-1
        jb15.setText(symbol);
        jb15.setEnabled(false);
        CLICKS++;
        
        setIndices(15); //save the index of this card to an array
        afterClick();
    }//GEN-LAST:event_jb15ActionPerformed

    private void jb16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb16ActionPerformed
        String symbol = Character.toString(symbols[15]); // index should be button#-1
        jb16.setText(symbol);
        jb16.setEnabled(false);
        CLICKS++;
        
        setIndices(16); //save the index of this card to an array
        afterClick();
    }//GEN-LAST:event_jb16ActionPerformed

    private void jb17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb17ActionPerformed
        String symbol = Character.toString(symbols[16]); // index should be button#-1
        jb17.setText(symbol);
        jb17.setEnabled(false);
        CLICKS++;
        
        setIndices(17); //save the index of this card to an array
        afterClick();
    }//GEN-LAST:event_jb17ActionPerformed

    private void jb18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb18ActionPerformed
        String symbol = Character.toString(symbols[17]); // index should be button#-1
        jb18.setText(symbol);
        jb18.setEnabled(false);
        CLICKS++;
        
        setIndices(18); //save the index of this card to an array
        afterClick();
    }//GEN-LAST:event_jb18ActionPerformed

    private void jb19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb19ActionPerformed
        String symbol = Character.toString(symbols[18]); // index should be button#-1
        jb19.setText(symbol);
        jb19.setEnabled(false);
        CLICKS++;
        
        setIndices(19); //save the index of this card to an array
        afterClick();
    }//GEN-LAST:event_jb19ActionPerformed

    private void jb20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb20ActionPerformed
        String symbol = Character.toString(symbols[19]); // index should be button#-1
        jb20.setText(symbol);
        jb20.setEnabled(false);
        CLICKS++;
        
        setIndices(20); //save the index of this card to an array
        afterClick();
    }//GEN-LAST:event_jb20ActionPerformed

    private void jb21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb21ActionPerformed
       String symbol = Character.toString(symbols[20]); // index should be button#-1
        jb21.setText(symbol);
        jb21.setEnabled(false);
        CLICKS++;
        
        setIndices(21); //save the index of this card to an array
        afterClick();
    }//GEN-LAST:event_jb21ActionPerformed

    private void jb22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb22ActionPerformed
        String symbol = Character.toString(symbols[21]); // index should be button#-1
        jb22.setText(symbol);
        jb22.setEnabled(false);
        CLICKS++;
        
        setIndices(22); //save the index of this card to an array
        afterClick();
    }//GEN-LAST:event_jb22ActionPerformed

    private void jb23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb23ActionPerformed
        String symbol = Character.toString(symbols[22]); // index should be button#-1
        jb23.setText(symbol);
        jb23.setEnabled(false);
        CLICKS++;
        
        setIndices(23); //save the index of this card to an array
        afterClick();
    }//GEN-LAST:event_jb23ActionPerformed

    private void jb24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb24ActionPerformed
       String symbol = Character.toString(symbols[23]); // index should be button#-1
        jb24.setText(symbol);
        jb24.setEnabled(false);
        CLICKS++;
        
        setIndices(24); //save the index of this card to an array
        afterClick();
    }//GEN-LAST:event_jb24ActionPerformed

    private void jb25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb25ActionPerformed
        String symbol = Character.toString(symbols[24]); // index should be button#-1
        jb25.setText(symbol);
        jb25.setEnabled(false);
        CLICKS++;
        
        setIndices(25); //save the index of this card to an array
        afterClick();
    }//GEN-LAST:event_jb25ActionPerformed

    private void jb26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb26ActionPerformed
        String symbol = Character.toString(symbols[25]); // index should be button#-1
        jb26.setText(symbol);
        jb26.setEnabled(false);
        CLICKS++;
        
        setIndices(26); //save the index of this card to an array
        afterClick();
    }//GEN-LAST:event_jb26ActionPerformed

    private void jb27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb27ActionPerformed
        String symbol = Character.toString(symbols[26]); // index should be button#-1
        jb27.setText(symbol);
        jb27.setEnabled(false);
        CLICKS++;
        
        setIndices(27); //save the index of this card to an array
        afterClick();
    }//GEN-LAST:event_jb27ActionPerformed

    private void jb28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb28ActionPerformed
        String symbol = Character.toString(symbols[27]); // index should be button#-1
        jb28.setText(symbol);
        jb28.setEnabled(false);
        CLICKS++;
        
        setIndices(28); //save the index of this card to an array
        afterClick();
    }//GEN-LAST:event_jb28ActionPerformed

    private void jb29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb29ActionPerformed
        String symbol = Character.toString(symbols[28]); // index should be button#-1
        jb29.setText(symbol);
        jb29.setEnabled(false);
        CLICKS++;
        
        setIndices(29); //save the index of this card to an array
        afterClick();
    }//GEN-LAST:event_jb29ActionPerformed

    private void jb30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb30ActionPerformed
        String symbol = Character.toString(symbols[29]); // index should be button#-1
        jb30.setText(symbol);
        jb30.setEnabled(false);
        CLICKS++;
        
        setIndices(30); //save the index of this card to an array
        afterClick();
    }//GEN-LAST:event_jb30ActionPerformed

    private void jb31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb31ActionPerformed
       String symbol = Character.toString(symbols[30]); // index should be button#-1
        jb31.setText(symbol);
        jb31.setEnabled(false);
        CLICKS++;
        
        setIndices(31); //save the index of this card to an array
        afterClick();
    }//GEN-LAST:event_jb31ActionPerformed

    private void jb32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb32ActionPerformed
        String symbol = Character.toString(symbols[31]); // index should be button#-1
        jb32.setText(symbol);
        jb32.setEnabled(false);
        CLICKS++;
        
        setIndices(32); //save the index of this card to an array
        afterClick();
    }//GEN-LAST:event_jb32ActionPerformed

    private void jb33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb33ActionPerformed
        String symbol = Character.toString(symbols[32]); // index should be button#-1
        jb33.setText(symbol);
        jb33.setEnabled(false);
        CLICKS++;
        
        setIndices(33); //save the index of this card to an array
        afterClick();
    }//GEN-LAST:event_jb33ActionPerformed

    private void jb34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb34ActionPerformed
        String symbol = Character.toString(symbols[33]); // index should be button#-1
        jb34.setText(symbol);
        jb34.setEnabled(false);
        CLICKS++;
        
        setIndices(34); //save the index of this card to an array
        afterClick();
    }//GEN-LAST:event_jb34ActionPerformed

    private void jb35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb35ActionPerformed
        String symbol = Character.toString(symbols[34]); // index should be button#-1
        jb35.setText(symbol);
        jb35.setEnabled(false);
        CLICKS++;
        
        setIndices(35); //save the index of this card to an array
        afterClick();
    }//GEN-LAST:event_jb35ActionPerformed

    private void jb36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb36ActionPerformed
        String symbol = Character.toString(symbols[35]); // index should be button#-1
        jb36.setText(symbol);
        jb36.setEnabled(false);
        CLICKS++;
        
        setIndices(36); //save the index of this card to an array
        afterClick();
    }//GEN-LAST:event_jb36ActionPerformed

    private void jb37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb37ActionPerformed
        String symbol = Character.toString(symbols[36]); // index should be button#-1
        jb37.setText(symbol);
        jb37.setEnabled(false);
        CLICKS++;
        
        setIndices(37); //save the index of this card to an array
        afterClick();
    }//GEN-LAST:event_jb37ActionPerformed

    private void jb38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb38ActionPerformed
        String symbol = Character.toString(symbols[37]); // index should be button#-1
        jb38.setText(symbol);
        jb38.setEnabled(false);
        CLICKS++;
        
        setIndices(38); //save the index of this card to an array
        afterClick();
    }//GEN-LAST:event_jb38ActionPerformed

    private void jb39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb39ActionPerformed
        String symbol = Character.toString(symbols[38]); // index should be button#-1
        jb39.setText(symbol);
        jb39.setEnabled(false);
        CLICKS++;
        
        setIndices(39); //save the index of this card to an array
        afterClick();
    }//GEN-LAST:event_jb39ActionPerformed

    private void jb40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb40ActionPerformed
        String symbol = Character.toString(symbols[39]); // index should be button#-1
        jb40.setText(symbol);
        jb40.setEnabled(false);
        CLICKS++;
        
        setIndices(40); //save the index of this card to an array
        afterClick();
    }//GEN-LAST:event_jb40ActionPerformed

    private void jb41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb41ActionPerformed
        String symbol = Character.toString(symbols[40]); // index should be button#-1
        jb41.setText(symbol);
        jb41.setEnabled(false);
        CLICKS++;
        
        setIndices(41); //save the index of this card to an array
        afterClick();
    }//GEN-LAST:event_jb41ActionPerformed

    private void jb42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb42ActionPerformed
        String symbol = Character.toString(symbols[41]); // index should be button#-1
        jb42.setText(symbol);
        jb42.setEnabled(false);
        CLICKS++;
        
        setIndices(42); //save the index of this card to an array
        afterClick();
    }//GEN-LAST:event_jb42ActionPerformed

    private void jb43ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb43ActionPerformed
        String symbol = Character.toString(symbols[42]); // index should be button#-1
        jb43.setText(symbol);
        jb43.setEnabled(false);
        CLICKS++;
        
        setIndices(43); //save the index of this card to an array
        afterClick();
    }//GEN-LAST:event_jb43ActionPerformed

    private void jb44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb44ActionPerformed
        String symbol = Character.toString(symbols[43]); // index should be button#-1
        jb44.setText(symbol);
        jb44.setEnabled(false);
        CLICKS++;
        
        setIndices(44); //save the index of this card to an array
        afterClick();
    }//GEN-LAST:event_jb44ActionPerformed

    private void jb45ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb45ActionPerformed
        String symbol = Character.toString(symbols[44]); // index should be button#-1
        jb45.setText(symbol);
        jb45.setEnabled(false);
        CLICKS++;
        
        setIndices(45); //save the index of this card to an array
        afterClick();
    }//GEN-LAST:event_jb45ActionPerformed

    private void jb46ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb46ActionPerformed
        String symbol = Character.toString(symbols[45]); // index should be button#-1
        jb46.setText(symbol);
        jb46.setEnabled(false);
        CLICKS++;
        
        setIndices(46); //save the index of this card to an array
        afterClick();
    }//GEN-LAST:event_jb46ActionPerformed

    private void jb47ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb47ActionPerformed
        String symbol = Character.toString(symbols[46]); // index should be button#-1
        jb47.setText(symbol);
        jb47.setEnabled(false);
        CLICKS++;
        
        setIndices(47); //save the index of this card to an array
        afterClick();
    }//GEN-LAST:event_jb47ActionPerformed

    private void jb48ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb48ActionPerformed
        String symbol = Character.toString(symbols[47]); // index should be button#-1
        jb48.setText(symbol);
        jb48.setEnabled(false);
        CLICKS++;
        
        setIndices(48); //save the index of this card to an array
        afterClick();
    }//GEN-LAST:event_jb48ActionPerformed

    private void jbNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNextActionPerformed
        setBoard();
        
        //determines whether to show the end game stuff
        if (matchedGame == board.getTotalMatches()){
            jLabel4.setText("RESULTS");
             if (P2.getMatches()>P1.getMatches()){
               jlP2Matches.setText("YOU WON!");
               jlP1Matches.setText("");
             }
            else if (P1.getMatches()>P2.getMatches()){
               jlP1Matches.setText("YOU WON!");
               jlP2Matches.setText("");}
            else {jlP1Matches.setText("Tie");
            jlP2Matches.setText("Tie");}
            jlInstructions.setText("Thank you for playing Memory! To play again click Main Menu.");
        }
    }//GEN-LAST:event_jbNextActionPerformed

    public void buttonsStatusHandler(int[] index1st, int[] index2nd){
    
    }
    
    public void trial(){
        jb1.setText("trial");
    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jb1;
    private javax.swing.JButton jb10;
    private javax.swing.JButton jb11;
    private javax.swing.JButton jb12;
    private javax.swing.JButton jb13;
    private javax.swing.JButton jb14;
    private javax.swing.JButton jb15;
    private javax.swing.JButton jb16;
    private javax.swing.JButton jb17;
    private javax.swing.JButton jb18;
    private javax.swing.JButton jb19;
    private javax.swing.JButton jb2;
    private javax.swing.JButton jb20;
    private javax.swing.JButton jb21;
    private javax.swing.JButton jb22;
    private javax.swing.JButton jb23;
    private javax.swing.JButton jb24;
    private javax.swing.JButton jb25;
    private javax.swing.JButton jb26;
    private javax.swing.JButton jb27;
    private javax.swing.JButton jb28;
    private javax.swing.JButton jb29;
    private javax.swing.JButton jb3;
    private javax.swing.JButton jb30;
    private javax.swing.JButton jb31;
    private javax.swing.JButton jb32;
    private javax.swing.JButton jb33;
    private javax.swing.JButton jb34;
    private javax.swing.JButton jb35;
    private javax.swing.JButton jb36;
    private javax.swing.JButton jb37;
    private javax.swing.JButton jb38;
    private javax.swing.JButton jb39;
    private javax.swing.JButton jb4;
    private javax.swing.JButton jb40;
    private javax.swing.JButton jb41;
    private javax.swing.JButton jb42;
    private javax.swing.JButton jb43;
    private javax.swing.JButton jb44;
    private javax.swing.JButton jb45;
    private javax.swing.JButton jb46;
    private javax.swing.JButton jb47;
    private javax.swing.JButton jb48;
    private javax.swing.JButton jb5;
    private javax.swing.JButton jb6;
    private javax.swing.JButton jb7;
    private javax.swing.JButton jb8;
    private javax.swing.JButton jb9;
    private javax.swing.JButton jbHelp;
    private javax.swing.JButton jbMainMenu;
    private javax.swing.JButton jbNext;
    private javax.swing.JButton jbQuit;
    private javax.swing.JLabel jlFirstTurn;
    private javax.swing.JLabel jlInstructions;
    private javax.swing.JLabel jlMTitle;
    private javax.swing.JLabel jlP1Matches;
    private javax.swing.JLabel jlP1Name;
    private javax.swing.JLabel jlP2Matches;
    private javax.swing.JLabel jlP2Name;
    javax.swing.JPanel jpGamePlayInstructions;
    private javax.swing.JPanel jpMGameArea;
    private javax.swing.JPanel jpMTitle;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the indexTurn
     */
    public int[] getIndexTurn() {
        return indexTurn;
    }

    /**
     * @param indexTurn the indexTurn to set
     */
    public void setIndexTurn(int[] indexTurn) {
        this.indexTurn = indexTurn;
    }
}
