/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package citbyui.cit260.sarahjanis.memory.frames;

/**
 *
 * @author Janis
 */

import citbyui.cit260.sarahjanis.memory.controls.Game;
import citbyui.cit260.sarahjanis.memory.exceptions.BoardException;
import citbyui.cit260.sarahjanis.memory.models.Board;
import citbyui.cit260.sarahjanis.memory.models.Card;
import citbyui.cit260.sarahjanis.memory.models.Player;
import citbyui.cit260.sarahjanis.memory.models.SymbolArray;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

public class BoardSmallFrame extends javax.swing.JFrame {
    private char symbols[];
     private int indexTurn[] = new int[2];
    Game game;
    Board board;
    SymbolArray symArr;
    Player P1;
    Player P2;
    Card card1;
    Card card2;
    boolean matched = false;
    //BoardLargeFrame lFrame;
    private int tCounter=1;
    private int CLICKS;
    
    //SymbolArray myArray = new SymbolArray();
    /**
     * Creates new form GameBoardFrame
     */
    public BoardSmallFrame(Player player1, Player player2, char getSymbols[]) throws BoardException{
        P1 = player1;
        P2 = player2;
        initComponents();
        setLocationRelativeTo(null);
        symbols = getSymbols;
        CLICKS = 0;
        
        jlP1Name.setText(P1.getName());
        jlP2Name.setText(P2.getName());
        
        jlInstructions.setText(P1.getName() + ": Choose a card.");        
        jbNext.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpTitle = new javax.swing.JPanel();
        jlTitle = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jlP1Name = new javax.swing.JLabel();
        jlP2Name = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jlP1Matches = new javax.swing.JLabel();
        jlP2Matches = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jlP1Wins = new javax.swing.JLabel();
        jlP2Wins = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jbMainMenu = new javax.swing.JButton();
        jbHelp = new javax.swing.JButton();
        jbQuit = new javax.swing.JButton();
        jpGamePlayInstructions = new javax.swing.JPanel();
        jlFirstTurn = new javax.swing.JLabel();
        jlInstructions = new javax.swing.JLabel();
        jbNext = new javax.swing.JButton();
        jpSGameArea = new javax.swing.JPanel();
        jb1 = new javax.swing.JButton();
        jb2 = new javax.swing.JButton();
        jb3 = new javax.swing.JButton();
        jb4 = new javax.swing.JButton();
        jb5 = new javax.swing.JButton();
        jb6 = new javax.swing.JButton();
        jb7 = new javax.swing.JButton();
        jb8 = new javax.swing.JButton();
        jb9 = new javax.swing.JButton();
        jb10 = new javax.swing.JButton();
        jb11 = new javax.swing.JButton();
        jb12 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Memory Game Small Grid");
        setBackground(new java.awt.Color(204, 255, 255));

        jpTitle.setBackground(new java.awt.Color(204, 255, 255));

        jlTitle.setBackground(new java.awt.Color(204, 255, 255));
        jlTitle.setFont(new java.awt.Font("Berlin Sans FB", 0, 36)); // NOI18N
        jlTitle.setForeground(new java.awt.Color(0, 153, 153));
        jlTitle.setText("MEMORY");

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setText("Player");

        jlP1Name.setText("Player 1:");

        jlP2Name.setText("Player 2:");

        jLabel4.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 153));
        jLabel4.setText("Matches");

        jlP1Matches.setText("0");

        jlP2Matches.setText("0");

        jLabel7.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 153, 153));
        jLabel7.setText("Wins");

        jlP1Wins.setText("0");

        jlP2Wins.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jlP1Name)
                    .addComponent(jlP2Name))
                .addGap(66, 66, 66)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jlP1Matches)
                    .addComponent(jlP2Matches))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlP2Wins)
                    .addComponent(jlP1Wins)
                    .addComponent(jLabel7))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlP1Name)
                    .addComponent(jlP1Matches)
                    .addComponent(jlP1Wins))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlP2Name)
                    .addComponent(jlP2Matches)
                    .addComponent(jlP2Wins))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));

        jbMainMenu.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jbMainMenu.setForeground(new java.awt.Color(0, 153, 153));
        jbMainMenu.setText("MAIN MENU");
        jbMainMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbMainMenuActionPerformed(evt);
            }
        });

        jbHelp.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jbHelp.setForeground(new java.awt.Color(0, 153, 153));
        jbHelp.setText("HELP");
        jbHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbHelpActionPerformed(evt);
            }
        });

        jbQuit.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jbQuit.setForeground(new java.awt.Color(0, 153, 153));
        jbQuit.setText("QUIT");
        jbQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbQuitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbHelp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbQuit, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbMainMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jbMainMenu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbHelp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbQuit)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jpGamePlayInstructions.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout jpGamePlayInstructionsLayout = new javax.swing.GroupLayout(jpGamePlayInstructions);
        jpGamePlayInstructions.setLayout(jpGamePlayInstructionsLayout);
        jpGamePlayInstructionsLayout.setHorizontalGroup(
            jpGamePlayInstructionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpGamePlayInstructionsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlInstructions, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlFirstTurn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpGamePlayInstructionsLayout.setVerticalGroup(
            jpGamePlayInstructionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpGamePlayInstructionsLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jlFirstTurn)
                .addContainerGap())
            .addComponent(jlInstructions, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jbNext.setText("Next");
        jbNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpTitleLayout = new javax.swing.GroupLayout(jpTitle);
        jpTitle.setLayout(jpTitleLayout);
        jpTitleLayout.setHorizontalGroup(
            jpTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTitleLayout.createSequentialGroup()
                .addGroup(jpTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpTitleLayout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(jlTitle))
                    .addGroup(jpTitleLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jpGamePlayInstructions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbNext)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8))
        );
        jpTitleLayout.setVerticalGroup(
            jpTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTitleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jpTitleLayout.createSequentialGroup()
                        .addComponent(jlTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jpGamePlayInstructions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbNext, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jpSGameArea.setLayout(new java.awt.GridLayout(3, 4, 10, 10));

        jb1.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 36)); // NOI18N
        jb1.setForeground(new java.awt.Color(0, 153, 153));
        jb1.setText("1");
        jb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb1ActionPerformed(evt);
            }
        });
        jpSGameArea.add(jb1);

        jb2.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 36)); // NOI18N
        jb2.setForeground(new java.awt.Color(0, 153, 153));
        jb2.setText("2");
        jb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb2ActionPerformed(evt);
            }
        });
        jpSGameArea.add(jb2);

        jb3.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 36)); // NOI18N
        jb3.setForeground(new java.awt.Color(0, 153, 153));
        jb3.setText("3");
        jb3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb3ActionPerformed(evt);
            }
        });
        jpSGameArea.add(jb3);

        jb4.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 36)); // NOI18N
        jb4.setForeground(new java.awt.Color(0, 153, 153));
        jb4.setText("4");
        jb4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb4ActionPerformed(evt);
            }
        });
        jpSGameArea.add(jb4);

        jb5.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 36)); // NOI18N
        jb5.setForeground(new java.awt.Color(0, 153, 153));
        jb5.setText("5");
        jb5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb5ActionPerformed(evt);
            }
        });
        jpSGameArea.add(jb5);

        jb6.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 36)); // NOI18N
        jb6.setForeground(new java.awt.Color(0, 153, 153));
        jb6.setText("6");
        jb6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb6ActionPerformed(evt);
            }
        });
        jpSGameArea.add(jb6);

        jb7.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 36)); // NOI18N
        jb7.setForeground(new java.awt.Color(0, 153, 153));
        jb7.setText("7");
        jb7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb7ActionPerformed(evt);
            }
        });
        jpSGameArea.add(jb7);

        jb8.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 36)); // NOI18N
        jb8.setForeground(new java.awt.Color(0, 153, 153));
        jb8.setText("8");
        jb8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb8ActionPerformed(evt);
            }
        });
        jpSGameArea.add(jb8);

        jb9.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 36)); // NOI18N
        jb9.setForeground(new java.awt.Color(0, 153, 153));
        jb9.setText("9");
        jb9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb9ActionPerformed(evt);
            }
        });
        jpSGameArea.add(jb9);

        jb10.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 36)); // NOI18N
        jb10.setForeground(new java.awt.Color(0, 153, 153));
        jb10.setText("10");
        jb10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb10ActionPerformed(evt);
            }
        });
        jpSGameArea.add(jb10);

        jb11.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 36)); // NOI18N
        jb11.setForeground(new java.awt.Color(0, 153, 153));
        jb11.setText("11");
        jb11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb11ActionPerformed(evt);
            }
        });
        jpSGameArea.add(jb11);

        jb12.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 36)); // NOI18N
        jb12.setForeground(new java.awt.Color(0, 153, 153));
        jb12.setText("12");
        jb12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb12ActionPerformed(evt);
            }
        });
        jpSGameArea.add(jb12);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpSGameArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpSGameArea, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb1ActionPerformed
       
       String symbol = Character.toString(symbols[0]);
       jb1.setText(symbol);
    }//GEN-LAST:event_jb1ActionPerformed

    private void jb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb2ActionPerformed
        String symbol = Character.toString(symbols[1]);
       jb2.setText(symbol);
     //  if (jbSButton1)
    }//GEN-LAST:event_jb2ActionPerformed

    private void jb3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb3ActionPerformed
        String symbol = Character.toString(symbols[2]);
       jb3.setText(symbol);
    }//GEN-LAST:event_jb3ActionPerformed

    private void jb4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb4ActionPerformed
        String symbol = Character.toString(symbols[3]);
       jb4.setText(symbol);
    }//GEN-LAST:event_jb4ActionPerformed

    private void jb5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb5ActionPerformed
        String symbol = Character.toString(symbols[4]);
       jb5.setText(symbol);
    }//GEN-LAST:event_jb5ActionPerformed

    private void jb6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb6ActionPerformed
        String symbol = Character.toString(symbols[5]);
       jb6.setText(symbol);
    }//GEN-LAST:event_jb6ActionPerformed

    private void jb7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb7ActionPerformed
        String symbol = Character.toString(symbols[6]);
       jb7.setText(symbol);
    }//GEN-LAST:event_jb7ActionPerformed

    private void jb8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb8ActionPerformed
        String symbol = Character.toString(symbols[7]);
       jb8.setText(symbol);
    }//GEN-LAST:event_jb8ActionPerformed

    private void jb9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb9ActionPerformed
        String symbol = Character.toString(symbols[8]);
       jb9.setText(symbol);
    }//GEN-LAST:event_jb9ActionPerformed

    private void jb10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb10ActionPerformed
        String symbol = Character.toString(symbols[9]);
       jb10.setText(symbol);
    }//GEN-LAST:event_jb10ActionPerformed

    private void jb11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb11ActionPerformed
        String symbol = Character.toString(symbols[10]);
       jb11.setText(symbol);
    }//GEN-LAST:event_jb11ActionPerformed

    private void jb12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb12ActionPerformed
        String symbol = Character.toString(symbols[11]);
       jb12.setText(symbol);
    }//GEN-LAST:event_jb12ActionPerformed

    private void setIndices(int index){
        
        if (CLICKS == 1){
            indexTurn[0]= index;
            
        }
        else if (CLICKS ==2){
          indexTurn[1]= index;
        }
      
    }
    
    private boolean checkMatch(){
        
        if (symbols[indexTurn[0]]== symbols[indexTurn[1]])
          return true;
        else
            return false;
    }
    private void afterClick(){
        if (CLICKS == 2){
            matched = checkMatch();
            CLICKS =0;
            
            if (tCounter % 2 != 0){
                if (matched == true){
                     P1.setMatchedGame(P1.getMatchedGame()+1);
                     jlInstructions.setText(P1.getName() + ": Yay, you made a match! You get another turn.");
                     jlP1Matches.setText(Integer.toString(P1.getMatchedGame()));
                     jbNext.setVisible(true);
                        disableCards();
            
                    //jbLButton1.setText("");
                    }
                else {
                    //jbLButton1.setText("1"); 
                    jlInstructions.setText(P1.getName() + ": Sorry, not a match. Next player's turn.");
                    jbNext.setVisible(true);
                        disableCards();
            
                    //next player's turn
                    tCounter++;} 
        }
             
            else {
                if (matched == true){
                     P2.setMatchedGame(P2.getMatchedGame()+1);
                     jlInstructions.setText(P2.getName() + ": Yay, you made a match! You get another turn.");
                     jlP2Matches.setText(Integer.toString(P2.getMatchedGame()));
                    jbNext.setVisible(true);
                        disableCards();
            
                    //jbLButton1.setText("");
                    }
                else{
                    //jbLButton1.setText("1"); 
                    jlInstructions.setText(P2.getName() + ": Sorry, not a match. Next player's turn.");
                    jbNext.setVisible(true);
                        disableCards();
            
                    //next player's turn
                    tCounter++;} 
            }
        }
        else{
            if (tCounter % 2 != 0){
              jlInstructions.setText(P1.getName() + ": Choose another card.");  
            }
            else{
              jlInstructions.setText(P2.getName() + ": Choose another card.");
            }
        }
            
    }
    private void setBoard(){
        //make this fix cards somehow
        if (matched == false){
            if (indexTurn[0]==0 || indexTurn[1]==0){
               jb1.setText("1"); 
            }
            if (indexTurn[0]==1 || indexTurn[1]==1){
               jb2.setText("2"); 
            }
            if (indexTurn[0]==2 || indexTurn[1]==2){
               jb3.setText("3"); 
            }
            if (indexTurn[0]==3 || indexTurn[1]==3){
               jb4.setText("4"); 
            }
            if (indexTurn[0]==4 || indexTurn[1]==4){
               jb5.setText("5"); 
            }
            if (indexTurn[0]==5 || indexTurn[1]==5){
               jb6.setText("6"); 
            }
            if (indexTurn[0]==6 || indexTurn[1]==6){
               jb7.setText("7"); 
            }
            if (indexTurn[0]==7 || indexTurn[1]==7){
               jb8.setText("8"); 
            }
            matched = false;
            jbNext.setVisible(false); 
                enableCards();
                
                //player instructions
                if (tCounter % 2 != 0){
                    jlInstructions.setText(P1.getName() + ": Choose a card.");  
                    }
                else{
                    jlInstructions.setText(P2.getName() + ": Choose a card.");
                    }
                }
        else if (matched == true){
            if (indexTurn[0]==0 || indexTurn[1]==0){
               jb1.setVisible(false); 
            }
            if (indexTurn[0]==1 || indexTurn[1]==1){
               jb2.setVisible(false); 
            }
            if (indexTurn[0]==2 || indexTurn[1]==2){
               jb3.setVisible(false); 
            }
            if (indexTurn[0]==3 || indexTurn[1]==3){
               jb4.setVisible(false); 
            }
            if (indexTurn[0]==4 || indexTurn[1]==4){
               jb5.setVisible(false); 
            }
            if (indexTurn[0]==5 || indexTurn[1]==5){
               jb6.setVisible(false); 
            }
            if (indexTurn[0]==6 || indexTurn[1]==6){
               jb7.setVisible(false); 
            }
            if (indexTurn[0]==7 || indexTurn[1]==7){
               jb8.setVisible(false); 
            }
            jbNext.setVisible(false);
                enableCards();
                
                //player instructions
                if (tCounter % 2 != 0){
                    jlInstructions.setText(P1.getName() + ": Choose a card.");  
                    }
                else{
                    jlInstructions.setText(P2.getName() + ": Choose a card.");
                    }
                }
        
    }
    
    private void disableCards(){
        jb1.setEnabled(false);
        jb2.setEnabled(false);
        jb3.setEnabled(false);
        jb4.setEnabled(false);
        jb5.setEnabled(false);
        jb6.setEnabled(false);
        jb7.setEnabled(false);
        jb8.setEnabled(false);
    }
    private void enableCards(){
        jb1.setEnabled(true);
        jb2.setEnabled(true);
        jb3.setEnabled(true);
        jb4.setEnabled(true);
        jb5.setEnabled(true);
        jb6.setEnabled(true);
        jb7.setEnabled(true);
        jb8.setEnabled(true);
    }
    
    private void jbMainMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMainMenuActionPerformed
        this.dispose();
        MainFrame mainFrame =  new MainFrame();
        mainFrame.setVisible(true);
    }//GEN-LAST:event_jbMainMenuActionPerformed

    private void jbHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbHelpActionPerformed
        HelpFrame helpFrame = new HelpFrame();
        helpFrame.setVisible(true);
    }//GEN-LAST:event_jbHelpActionPerformed

    private void jbQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbQuitActionPerformed
        this.dispose();
    }//GEN-LAST:event_jbQuitActionPerformed

    private void jbNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNextActionPerformed
        setBoard();
    }//GEN-LAST:event_jbNextActionPerformed

    
    /*public void firstTurn(Player player1, Player player2){
        
   jlFirstTurn.setText(player1.getName() + ", pick your first card");
  // }
    
    
   // public void createCards(){/*
  /*  jpTitle.setVisible(true);
    JButton buttonT = new JButton("4 title panel");
    JButton buttonGB = new JButton("4 game panel");
    jpTitle.add(buttonT);
    
    jpGameArea.add(buttonGB);
   // buttonGB.setText("I'M A manually added BUTTON IN THE GAME PANEL");
    
    //layout.*/
//}
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jb1;
    private javax.swing.JButton jb10;
    private javax.swing.JButton jb11;
    private javax.swing.JButton jb12;
    private javax.swing.JButton jb2;
    private javax.swing.JButton jb3;
    private javax.swing.JButton jb4;
    private javax.swing.JButton jb5;
    private javax.swing.JButton jb6;
    private javax.swing.JButton jb7;
    private javax.swing.JButton jb8;
    private javax.swing.JButton jb9;
    private javax.swing.JButton jbHelp;
    private javax.swing.JButton jbMainMenu;
    private javax.swing.JButton jbNext;
    private javax.swing.JButton jbQuit;
    private javax.swing.JLabel jlFirstTurn;
    private javax.swing.JLabel jlInstructions;
    private javax.swing.JLabel jlP1Matches;
    private javax.swing.JLabel jlP1Name;
    private javax.swing.JLabel jlP1Wins;
    private javax.swing.JLabel jlP2Matches;
    private javax.swing.JLabel jlP2Name;
    private javax.swing.JLabel jlP2Wins;
    private javax.swing.JLabel jlTitle;
    javax.swing.JPanel jpGamePlayInstructions;
    private javax.swing.JPanel jpSGameArea;
    private javax.swing.JPanel jpTitle;
    // End of variables declaration//GEN-END:variables
}
