/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package citbyui.cit260.sarahjanis.memory.frames;

import citbyui.cit260.sarahjanis.memory.controls.HelpMenuControl;
import citbyui.cit260.sarahjanis.memory.enums.HelpType;
import citbyui.cit260.sarahjanis.memory.exceptions.MemoryException;

/**
 *
 * @author Janis
 */
public class HelpFrame extends javax.swing.JFrame {
    HelpMenuControl helpCommands = new HelpMenuControl();

    /**
     * Creates new form HelpFrame
     */
    public HelpFrame() {
        initComponents();
        setLocationRelativeTo(null);
        
    }
    
     public HelpMenuControl getHelpCommands() {
        return helpCommands;
    }


    
    private void displayHelpText(HelpType command) {
        try {
            String helpText = this.helpCommands.getHelpText(command);
            this.jtHelpText.setText(helpText);
        } catch (MemoryException ex) {
            this.jtHelpText.setText(ex.getMessage());
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpHelpBody = new javax.swing.JPanel();
        jpHelpTitle = new javax.swing.JPanel();
        jlHelpTitle = new javax.swing.JLabel();
        jpHelpMenuItems = new javax.swing.JPanel();
        jbHelpDifficultyLevels = new javax.swing.JButton();
        jbHelpGame = new javax.swing.JButton();
        jbHelpChoosingCards = new javax.swing.JButton();
        jbReturnToMain = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtHelpText = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HELP MENU");
        setPreferredSize(new java.awt.Dimension(501, 414));

        jpHelpBody.setBackground(new java.awt.Color(204, 255, 255));
        jpHelpBody.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 255, 255), 1, true));
        jpHelpBody.setPreferredSize(new java.awt.Dimension(501, 414));

        jpHelpTitle.setBackground(new java.awt.Color(204, 255, 255));

        jlHelpTitle.setFont(new java.awt.Font("Berlin Sans FB", 0, 36)); // NOI18N
        jlHelpTitle.setForeground(new java.awt.Color(0, 153, 153));
        jlHelpTitle.setText("Help Menu");

        javax.swing.GroupLayout jpHelpTitleLayout = new javax.swing.GroupLayout(jpHelpTitle);
        jpHelpTitle.setLayout(jpHelpTitleLayout);
        jpHelpTitleLayout.setHorizontalGroup(
            jpHelpTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpHelpTitleLayout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(jlHelpTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpHelpTitleLayout.setVerticalGroup(
            jpHelpTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlHelpTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jpHelpMenuItems.setBackground(new java.awt.Color(204, 255, 255));
        jpHelpMenuItems.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 255, 255), new java.awt.Color(0, 102, 102)));

        jbHelpDifficultyLevels.setText("DIFFICULTY");
        jbHelpDifficultyLevels.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbHelpDifficultyLevelsActionPerformed(evt);
            }
        });

        jbHelpGame.setText("HOW TO PLAY");
        jbHelpGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbHelpGameActionPerformed(evt);
            }
        });

        jbHelpChoosingCards.setText("CHOOSING CARDS");
        jbHelpChoosingCards.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbHelpChoosingCardsActionPerformed(evt);
            }
        });

        jbReturnToMain.setText("EXIT HELP");
        jbReturnToMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbReturnToMainActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpHelpMenuItemsLayout = new javax.swing.GroupLayout(jpHelpMenuItems);
        jpHelpMenuItems.setLayout(jpHelpMenuItemsLayout);
        jpHelpMenuItemsLayout.setHorizontalGroup(
            jpHelpMenuItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpHelpMenuItemsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpHelpMenuItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbHelpChoosingCards, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbHelpDifficultyLevels, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbHelpGame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbReturnToMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpHelpMenuItemsLayout.setVerticalGroup(
            jpHelpMenuItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpHelpMenuItemsLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jbHelpGame)
                .addGap(18, 18, 18)
                .addComponent(jbHelpChoosingCards)
                .addGap(18, 18, 18)
                .addComponent(jbHelpDifficultyLevels)
                .addGap(18, 18, 18)
                .addComponent(jbReturnToMain)
                .addContainerGap(166, Short.MAX_VALUE))
        );

        jtHelpText.setEditable(false);
        jtHelpText.setColumns(20);
        jtHelpText.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jtHelpText.setLineWrap(true);
        jtHelpText.setRows(5);
        jtHelpText.setWrapStyleWord(true);
        jtHelpText.setMargin(new java.awt.Insets(8, 8, 8, 8));
        jScrollPane1.setViewportView(jtHelpText);

        javax.swing.GroupLayout jpHelpBodyLayout = new javax.swing.GroupLayout(jpHelpBody);
        jpHelpBody.setLayout(jpHelpBodyLayout);
        jpHelpBodyLayout.setHorizontalGroup(
            jpHelpBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpHelpTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jpHelpBodyLayout.createSequentialGroup()
                .addComponent(jpHelpMenuItems, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpHelpBodyLayout.setVerticalGroup(
            jpHelpBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpHelpBodyLayout.createSequentialGroup()
                .addComponent(jpHelpTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpHelpBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpHelpMenuItems, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpHelpBody, javax.swing.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpHelpBody, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbHelpGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbHelpGameActionPerformed
         displayHelpText(HelpType.INSTRUCTIONS);
    }//GEN-LAST:event_jbHelpGameActionPerformed

    private void jbHelpChoosingCardsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbHelpChoosingCardsActionPerformed
         displayHelpText(HelpType.CHOOSE_CARDS);
    }//GEN-LAST:event_jbHelpChoosingCardsActionPerformed

    private void jbHelpDifficultyLevelsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbHelpDifficultyLevelsActionPerformed
         displayHelpText(HelpType.DIFFICULTY);
    }//GEN-LAST:event_jbHelpDifficultyLevelsActionPerformed

    private void jbReturnToMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbReturnToMainActionPerformed
        this.dispose();
    }//GEN-LAST:event_jbReturnToMainActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbHelpChoosingCards;
    private javax.swing.JButton jbHelpDifficultyLevels;
    private javax.swing.JButton jbHelpGame;
    private javax.swing.JButton jbReturnToMain;
    private javax.swing.JLabel jlHelpTitle;
    private javax.swing.JPanel jpHelpBody;
    private javax.swing.JPanel jpHelpMenuItems;
    private javax.swing.JPanel jpHelpTitle;
    private javax.swing.JTextArea jtHelpText;
    // End of variables declaration//GEN-END:variables
}
