/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package citbyui.cit260.sarahjanis.memory.frames;

import citbyui.cit260.sarahjanis.memory.controls.Game;
import citbyui.cit260.sarahjanis.memory.enums.ErrorType;
import citbyui.cit260.sarahjanis.memory.exceptions.BoardException;
import citbyui.cit260.sarahjanis.memory.exceptions.CardException;
import citbyui.cit260.sarahjanis.memory.exceptions.MemoryException;
import citbyui.cit260.sarahjanis.memory.models.Board;
import citbyui.cit260.sarahjanis.memory.models.MemoryError;
import citbyui.cit260.sarahjanis.memory.models.Player;
import citbyui.cit260.sarahjanis.memory.models.SymbolArray;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Janis
 */
public class OptionFrame extends javax.swing.JFrame {
    private Board board = new Board();
    private SymbolArray symbols = new SymbolArray();
    private Player player1 = new Player();
    private Player player2 = new Player();
    private Game game = new Game();
    
    /**
     * Creates new form OptionFrame
     */
    public OptionFrame() {
        initComponents();
        setLocationRelativeTo(null);
        jpError.setVisible(false);
        jpError2.setVisible(false);
        jpError2.setVisible(false);
        jlErrorGrid.setVisible(false);
        jlErrorName.setVisible(false);
        jlErrorSize.setVisible(false);
        jBReset.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpOptions = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jbTwoCards = new javax.swing.JButton();
        jbFourCards = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jbSmall = new javax.swing.JButton();
        jbMedium = new javax.swing.JButton();
        jbLarge = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtfP1Name = new javax.swing.JTextField();
        jtfP2Name = new javax.swing.JTextField();
        jpError = new javax.swing.JPanel();
        jlErrorGrid = new javax.swing.JLabel();
        jpError2 = new javax.swing.JPanel();
        jlErrorName = new javax.swing.JLabel();
        jPError3 = new javax.swing.JPanel();
        jlErrorSize = new javax.swing.JLabel();
        jBReset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpOptions.setBackground(new java.awt.Color(204, 255, 255));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 102, 102));
        jButton1.setText("DEAL THE CARDS");
        jButton1.setToolTipText("");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setText("OPTIONS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(20, 20, 20))
        );

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("How many of each card?");

        jbTwoCards.setText("2");
        jbTwoCards.setToolTipText("");
        jbTwoCards.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbTwoCardsActionPerformed(evt);
            }
        });

        jbFourCards.setText("4");
        jbFourCards.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbFourCardsActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("What size grid?");

        jbSmall.setText("SMALL");
        jbSmall.setToolTipText("12 cards ");
        jbSmall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSmallActionPerformed(evt);
            }
        });

        jbMedium.setText("MEDIUM");
        jbMedium.setToolTipText("24 cards");
        jbMedium.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbMediumActionPerformed(evt);
            }
        });

        jbLarge.setText("LARGE");
        jbLarge.setToolTipText("48 cards");
        jbLarge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLargeActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 102));
        jLabel4.setText("Enter player names:");

        jLabel5.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jLabel5.setText("Player 1:");

        jLabel6.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jLabel6.setText("Player 2:");

        jpError.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 51), 2));
        jpError.setOpaque(false);

        javax.swing.GroupLayout jpErrorLayout = new javax.swing.GroupLayout(jpError);
        jpError.setLayout(jpErrorLayout);
        jpErrorLayout.setHorizontalGroup(
            jpErrorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpErrorLayout.createSequentialGroup()
                .addComponent(jlErrorGrid, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 33, Short.MAX_VALUE))
        );
        jpErrorLayout.setVerticalGroup(
            jpErrorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlErrorGrid, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
        );

        jpError2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 51), 2));
        jpError2.setOpaque(false);

        javax.swing.GroupLayout jpError2Layout = new javax.swing.GroupLayout(jpError2);
        jpError2.setLayout(jpError2Layout);
        jpError2Layout.setHorizontalGroup(
            jpError2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpError2Layout.createSequentialGroup()
                .addComponent(jlErrorName, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 32, Short.MAX_VALUE))
        );
        jpError2Layout.setVerticalGroup(
            jpError2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlErrorName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
        );

        jPError3.setOpaque(false);

        jlErrorSize.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 51), 2));

        javax.swing.GroupLayout jPError3Layout = new javax.swing.GroupLayout(jPError3);
        jPError3.setLayout(jPError3Layout);
        jPError3Layout.setHorizontalGroup(
            jPError3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPError3Layout.createSequentialGroup()
                .addComponent(jlErrorSize, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 22, Short.MAX_VALUE))
        );
        jPError3Layout.setVerticalGroup(
            jPError3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlErrorSize, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
        );

        jBReset.setBackground(new java.awt.Color(255, 255, 0));
        jBReset.setText("RESET YOUR OPTIONS");
        jBReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpOptionsLayout = new javax.swing.GroupLayout(jpOptions);
        jpOptions.setLayout(jpOptionsLayout);
        jpOptionsLayout.setHorizontalGroup(
            jpOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jpOptionsLayout.createSequentialGroup()
                .addGroup(jpOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpOptionsLayout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBReset))
                    .addGroup(jpOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jpOptionsLayout.createSequentialGroup()
                            .addGap(35, 35, 35)
                            .addGroup(jpOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jpOptionsLayout.createSequentialGroup()
                                    .addGroup(jpOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jbSmall)
                                        .addComponent(jLabel3)
                                        .addComponent(jbTwoCards))
                                    .addGap(18, 18, 18)
                                    .addGroup(jpOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jbMedium)
                                        .addComponent(jbFourCards))
                                    .addGap(18, 18, 18)
                                    .addGroup(jpOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jpOptionsLayout.createSequentialGroup()
                                            .addComponent(jbLarge)
                                            .addGap(18, 18, 18)
                                            .addComponent(jPError3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jpError, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(jLabel4)
                                .addGroup(jpOptionsLayout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addGroup(jpOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel5))
                                    .addGap(21, 21, 21)
                                    .addGroup(jpOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jtfP1Name, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jtfP2Name, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGroup(jpOptionsLayout.createSequentialGroup()
                            .addGap(26, 26, 26)
                            .addComponent(jLabel2))))
                .addGap(16, 114, Short.MAX_VALUE))
            .addGroup(jpOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpOptionsLayout.createSequentialGroup()
                    .addContainerGap(305, Short.MAX_VALUE)
                    .addComponent(jpError2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(55, 55, 55)))
        );
        jpOptionsLayout.setVerticalGroup(
            jpOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpOptionsLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtfP1Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jtfP2Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jpOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbTwoCards)
                        .addComponent(jbFourCards))
                    .addComponent(jpError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbSmall)
                        .addComponent(jbMedium)
                        .addComponent(jbLarge))
                    .addComponent(jPError3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jpOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBReset, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
            .addGroup(jpOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpOptionsLayout.createSequentialGroup()
                    .addGap(106, 106, 106)
                    .addComponent(jpError2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(255, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpOptions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpOptions, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        player1.setName(jtfP1Name.getText());
        player2.setName(jtfP2Name.getText());
        
        boolean check = inputCheck();
        if (check == false){
            /*jlError.setText("ERORR"
                     + "\nPlease make sure to enter and select all information."
                     + "\nNames need to be at least one character long.");*/
            OptionFrame options = new OptionFrame();
             options.setVisible(true);
            
        }
        else        
        try {
            game.startGame(board, player1, player2, symbols);
        } catch (IOException ex) {
            Logger.getLogger(OptionFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (CardException ex) {
            Logger.getLogger(OptionFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (BoardException ex) {
            Logger.getLogger(OptionFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (MemoryException ex) {
            Logger.getLogger(OptionFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jbSmallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSmallActionPerformed
        board.setSize("s");
        jbSmall.setFont(new java.awt.Font("Berlin Sans FB", 0, 20));
        jbMedium.setFont(new java.awt.Font("Tahoma", 0, 11));
        jbLarge.setFont(new java.awt.Font("Tahoma", 0, 11)); 
       
    }//GEN-LAST:event_jbSmallActionPerformed

    private void jbMediumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMediumActionPerformed
        board.setSize("m");
        jbMedium.setFont(new java.awt.Font("Berlin Sans FB", 0, 20));
        jbSmall.setFont(new java.awt.Font("Tahoma", 0, 11));
        jbLarge.setFont(new java.awt.Font("Tahoma", 0, 11));     
    }//GEN-LAST:event_jbMediumActionPerformed

    private void jbLargeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLargeActionPerformed
        board.setSize("l");
        jbLarge.setFont(new java.awt.Font("Berlin Sans FB", 0, 20));
        jbMedium.setFont(new java.awt.Font("Tahoma", 0, 11));
        jbSmall.setFont(new java.awt.Font("Tahoma", 0, 11));
    }//GEN-LAST:event_jbLargeActionPerformed

    private void jbTwoCardsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbTwoCardsActionPerformed
        symbols.setNumMatchingSymbols(2);
        jbTwoCards.setFont(new java.awt.Font("Berlin Sans FB", 0, 20));
        jbFourCards.setFont(new java.awt.Font("Tahoma", 0, 11));
    }//GEN-LAST:event_jbTwoCardsActionPerformed

    private void jbFourCardsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbFourCardsActionPerformed
        symbols.setNumMatchingSymbols(4);
        jbFourCards.setFont(new java.awt.Font("Berlin Sans FB", 0, 20));
        jbTwoCards.setFont(new java.awt.Font("Tahoma", 0, 11));
    }//GEN-LAST:event_jbFourCardsActionPerformed

    private void jBResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBResetActionPerformed
    /*    OptionFrame options = new OptionFrame();
             options.setVisible(true);*/
    }//GEN-LAST:event_jBResetActionPerformed

    /**
     * @param args the command line arguments
     */
    
private boolean inputCheck() {
    
    boolean namecheck = nameCheck(player1.getName());
    boolean namecheck2 = nameCheck(player2.getName());
    boolean boardSizeCheck = boardSizeCheck();
    boolean matchSymCheck = matchSymCheck();
     if(namecheck == false || namecheck2 == false || boardSizeCheck == false || matchSymCheck == false){
         jpError.setVisible(true);
             return false;
                }
     else
     return true;
}
    
private boolean nameCheck(String name){ 
        MemoryError errorMsg = new MemoryError();
        
            name = name.trim();
            
            if (name.length() < 1){
              errorMsg.displayError(ErrorType.ERROR104.getMessage());
              return false;
            }
            
            if ((name.equals("Computer"))||(name.equals("computer"))) {
                errorMsg.displayError("This is a reserved name. You can not use it."
                        + "\"Try again.");
               return false; 
            }
            
           /* if (alreadyUsed(listOfPlayerNames, name)){
                errorMsg.displayError("This name was already entered"
                        + "\"Try again.");
                
            }*/
            else
                return true;       
        }

private boolean boardSizeCheck(){
     MemoryError errorMsg = new MemoryError();
    if (!"s".equals(board.getSize()) && !"m".equals(board.getSize()) && !"l".equals(board.getSize())){
        errorMsg.displayError(ErrorType.ERROR102.getMessage());
        return false;
    }
    else
        return true;
}
private boolean matchSymCheck(){
    MemoryError errorMsg = new MemoryError();
    if (symbols.getNumMatchingSymbols() != 2 && symbols.getNumMatchingSymbols() != 4) {
        
        errorMsg.displayError(ErrorType.ERROR204.getMessage());
        return false;
    }
    else
        return true;
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBReset;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPError3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbFourCards;
    private javax.swing.JButton jbLarge;
    private javax.swing.JButton jbMedium;
    private javax.swing.JButton jbSmall;
    private javax.swing.JButton jbTwoCards;
    private javax.swing.JLabel jlErrorGrid;
    private javax.swing.JLabel jlErrorName;
    private javax.swing.JLabel jlErrorSize;
    private javax.swing.JPanel jpError;
    private javax.swing.JPanel jpError2;
    private javax.swing.JPanel jpOptions;
    private javax.swing.JTextField jtfP1Name;
    private javax.swing.JTextField jtfP2Name;
    // End of variables declaration//GEN-END:variables
}
